<a href="https://colab.research.google.com/github/OrthrusB/All-Sem/blob/main/Introduction/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to NumPy**

# what we will cover?


*   Creating arrays
*   multidimensional array
*   Randomly generated arrays
*   Element wise operations
*   Summarizing operations







# One dimensional array


In [19]:
import numpy as np
#create and array with all the element zeros

In [20]:
#element with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
#create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [22]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [23]:
arr=np.array([5, 6, 7, 8, 9])
arr[3]=10
print(arr)

[ 5  6  7 10  9]


In [31]:
#range diyera
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
#create array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Two Dimensional Array

In [27]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [40]:
a=np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
          )

a[0,1]=20
a


array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [39]:
print("\n")
a[2:3]=1
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [41]:
a[0,2]=2
a[1,2]=2
a[2,2]=2
print (a)

[[ 1 20  2]
 [ 4  5  2]
 [ 7  8  2]]


In [42]:
#all elements 10 of 3*3 matrix
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Randomly generated array
- NumPy can create arrays filled with random numbers
- To ensure the reporducibilitym you can set a seed using ```np.random.
seed()```. It will generate the exact same random numbers for each executions.
- If you remove or change the seed values , the sequence fo random numbers will be changed.


In [43]:
np.random.rand(5)

array([0.48954755, 0.4062465 , 0.88603365, 0.98789135, 0.53707879])

In [59]:
np.random.seed(80)
np.random.rand(5)
#randomly numbers generated always comes between 0 and 1

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [66]:
np.random.randn(5, 2)

array([[-0.23545288,  0.04447746],
       [ 0.68371182, -0.88236076],
       [ 0.43882123, -0.79216802],
       [ 1.44149913, -1.73100657],
       [-0.11842654,  0.9031765 ]])

In [68]:
np.random.randint(low=0, high=100,size=(5,2))

array([[33, 63],
       [ 9,  1],
       [27, 80],
       [55, 39],
       [76,  3]])

In [ ]:
print("hi babin")